### ISSUE TITLE
Clarify whether proposals should be submitted to SourceForge www.pivotaltracker.com or GitHub issues

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml.github.io#44]
It seems that the website is out of date. Some pages suggest issues should be posted to SourceForge www.pivotaltracker.com. However, the pivotaltracker website is empty. I believe this should be updated to point to GitHub issues.

**Comment by luciansmith** [comment]
Moved this item to the web site tracker instead of the spec tracker.
