### ISSUE TITLE
Change file extensions of SED-ML files in examples to `.sedml`

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml.github.io#57]
More typically, I've seen SED-ML files use the extension `.sedml`, with `.xml` used with SBML.

This shouldn't be necessary because their format should be captured by the `format` attribute in manifests. However, some tools are trying to be more permissive in their handling of COMBINE archives because it appears that some tools don't generate the format attribute and some people/tools don't produce manifests at all.

**Comment by matthiaskoenig** [comment]
I agree, we should use the `.sedml` extension whenever possible (leading by example) and encourage SED-ML users to do as well.
